Completed complexes.html and css
redelvis/yard-frontend pull request #1
Opened 2017-06-16 08:49 UTC by redelvis

2017-06-16 09:48 UTC, imevro requested changes
https://rawgit.com/redelvis/yard-frontend/develop/complexes.html

описание распидорасило
отступ у названия жк дикий
у реквизитов неправильный отступ
у купить снять наши агенты неправильный отступ
у дискавер посыпался шрифт тайтла

2017-06-17 10:28 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27252202-d3e8f736-5360-11e7-9e41-63a505ed6dab.png)

2017-06-17 10:35 UTC, imevro requested changes

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +        <p class="discover-text">Compass brings a modern approach to new development marketing and sales. From boutique rental conversions to luxurious ground-up condominiums, browse our portfolio of
тут должна быть сетка в 8 колонок, а не паддинг слева и справа. Тогда оно заработает как надо.

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +          <button class="button-contact">Contact The Team</button>
.discover > ... > .discover-title + .discover-text + .contact (?) > .button-contact (?)

Где согласованность?

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +         <a class="apt-card" href="#card1">
Это не апартаменты, это жк

И опять же согласованность

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +             <p class="card-loc">SOUTH BEACH, SAN FRANCISCO</p>
не экономь на байтах

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +               <h3 class="card-title">764 Metropolitan Avenue</h3>
уехала идентация

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +      <div class="grid">
1) уехала табуляция
2) а зачем класс грид?

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +                <span>Все ЖК Москвы</span>
1) спан не нужен
2) что с табуляцией опять

2017-06-17 10:35 UTC, evgenyrodionov commented on complexes.html
> +                <a class="footer-link" href="#">ВТБ Арена Парк</a>
да и тут плохо с табуляцией

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +.global-header-compass-logo {
почему глобал-хедер, если выше просто хедер?

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +  flex-flow: column;
а зачем?

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +  margin: 64px 128px;
не уловил что это за марджин слева и справа

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +.card:first-child {
а не проще не ставить марджин-топ у кардс тогда?

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +footer {
футер не эксклюзивный тег и может использоваться много раз на странице

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> +.grid {
слабый нейминг конечно

2017-06-17 10:35 UTC, evgenyrodionov commented on style.css
> + sans-serif
wtf

2017-06-17 10:35 UTC, evgenyrodionov commented
И очень плохо с табуляцией, конечно

2017-06-17 23:00 UTC, redelvis commented on complexes.html
> +                <span>Все ЖК Москвы</span>
пробовал без спана через <а>, тогда слетает цвет. Через <p> стрелка оказывается на след строчке

2017-06-18 00:49 UTC, imevro requested changes

2017-06-18 00:49 UTC, evgenyrodionov commented on style.css
> +  flex-flow: column;
соу

2017-06-18 09:18 UTC, redelvis commented on style.css
> +  flex-flow: column;
Я уже не помню зачем! Это же моя первая верстка. Верстаю и пробую значения в стилях методом научного тыка, пока не перестает ломаться. Сейчас убрал и вроде ничего не поломалось.

2017-06-18 11:43 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27260413-5afadc8e-5434-11e7-9786-76f522a6272e.png)

отступ большой

2017-06-18 11:43 UTC, evgenyrodionov commented
Пофикси — смерджу

2017-06-18 13:46 UTC, merged

2017-06-18 13:46 UTC, evgenyrodionov commented
Не забудь сделать гит фетч --олл и гит пулл ориджин мастер --ребейз где нужно (в мастере и в своём бранче где комплекс делаешь)